# Generated by Django 2.0.1 on 2018-08-22 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('season_num', models.IntegerField(default=0)),
                ('episode_num', models.IntegerField(default=0)),
                ('episode_name', models.CharField(max_length=100)),
                ('episode_len', models.DurationField()),
                ('air_datetime', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('year_created', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tweet_datetime', models.DateTimeField(verbose_name='date published')),
                ('tweet_id', models.IntegerField(db_index=True, default=0, unique=True)),
                ('text', models.CharField(max_length=200)),
                ('interval', models.DurationField()),
                ('truncated', models.BooleanField()),
                ('retweets', models.IntegerField(default=0)),
                ('favorites', models.IntegerField(default=0)),
                ('result_type', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rewyndapp.Episode')),
            ],
        ),
        migrations.CreateModel(
            name='Tweeter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('twitter_unique_id', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('screen_name', models.CharField(max_length=200)),
                ('followers', models.IntegerField(default=0)),
                ('statuses', models.IntegerField(default=0)),
                ('profile_image_url', models.URLField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='tweet',
            name='tweeter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rewyndapp.Tweeter'),
        ),
        migrations.AddField(
            model_name='episode',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rewyndapp.Program'),
        ),
    ]
