# Generated by Django 2.0.1 on 2018-08-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewyndapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_datetime',
            field=models.DateTimeField(verbose_name='date of tweet'),
        ),
    ]
