# Generated by Django 2.0.1 on 2018-09-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewyndapp', '0002_auto_20180822_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
