# Generated by Django 2.0.1 on 2018-09-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewyndapp', '0004_program_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='program',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tweeter',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
