# Generated by Django 2.0.1 on 2018-10-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewyndapp', '0006_tweet_is_retweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='has_media',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tweet',
            name='media_image_url',
            field=models.URLField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='media_type',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='result_type',
            field=models.CharField(default='None', max_length=40),
        ),
        migrations.AlterField(
            model_name='tweeter',
            name='profile_image_url',
            field=models.URLField(max_length=250),
        ),
    ]
